# Site settings
title: ebiyaSG
description: "Specialist Caridina shrimp tanks, shrimp care guides, and premium shrimp products in Singapore."
author: ebiyaSG

# GitHub Pages / Custom Domain
url: "https://www.ebiya.sg"
baseurl: "" # MUST be empty when using a custom domain

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-sitemap

# Social Media Links
instagram_url: https://www.instagram.com/ebiyasg
tiktok_url: https://www.tiktok.com/@fish_ah_gong
whatsapp_url: https://wa.me/6589002228

  
